### ISSUE TITLE
Double execution of scheduled jobs when multiple hosts are running

### ISSUE THREAD

**Issue by bbozo** [moove-it/sidekiq-scheduler#156] opened 2016-12-09 07:10 UTC
Three days ago we had a job run twice on 2 hosts after turning on Sidekiq on the 2nd host five days ago. We are using `sidekiq-scheduler (2.0.9)` and we set it up using this code in a non-Rails app:

``` ruby
Sidekiq.configure_server do |config|
  threads = config.options[:concurrency] = ( ENV['MAX_WORKER_THREADS'] || 4 ).to_i
  config.redis = ConnectionPool.new(size: threads + 1, &redis_conn)
  config.options[:verbose] = App.log.log_level == :debug

  # set up Sidekiq Scheduler
  config.on(:startup) do
    schedule = YAML.load_erb_file(App.root + "/config/scheduler.yml")
    Dir[App.root + "/modules/*/config/scheduler.yml"].each do |yaml|
      schedule.merge! YAML.load_erb_file(yaml)
    end

    Sidekiq.schedule = schedule
    Sidekiq::Scheduler.reload_schedule!
  end
end
```

This code has been working well for 6 months now before we added the 2nd host, the scheduler web interface shows that the jobs are correctly loaded.

If this helps, it's a very low latency environment, clocks synced perfectly, not an AWS/Heroku etc setup. However I always make sure that not all sidekiq's get restarted at the same time to avoid #154. I'm kind of afraid to try this again because the implications of a double run of a task are pretty terrifying in my use case.

I noticed today that a different user [makes sure not to run sidekiq scheduler on all machines](https://github.com/moove-it/sidekiq-scheduler/issues/147#issuecomment-255490978) yet there's nothing in the docs suggesting that this might be important.

**Comment by bbozo** [comment] 2016-12-09 07:41
I went through the code, it seems that this project simply uses Rufus to do the task running, but Rufus seemingly uses a file locking mechanism at the best and no locking at the worst so this would explain everything. I wrote to rufus people (that sounds wrong ^_^) to check out if there's any option to implement distributed locking in Rufus that could maybe be used in `sidekiq-scheduler`

But in the meantime, we need a big fat juicy warning for this and an example scheduling code that takes this into account.

**Comment by bbozo** [comment] 2016-12-09 07:50
Seems that yes, Rufus supports dependency injection for the locking mechanism (https://github.com/jmettraux/rufus-scheduler/blob/master/lib/rufus/scheduler.rb#L101 + https://github.com/jmettraux/rufus-scheduler/blob/master/lib/rufus/scheduler/locks.rb), and there's an official Redis locking lib for Ruby https://github.com/leandromoreira/redlock-rb

**Comment by bbozo** [comment] 2016-12-09 08:48
Indeed, this one seems much easier to implement than to test, first problem will be redis faker because `redlock-rb` sends actual command strings to redis, not just interfacing via the `redis` gem. I guess we'd have to move away from this if we want distributed locking in place, so I'll defer this judgement to the big guys here :)

**Comment by snmgian** [comment] 2016-12-09 20:23
Hi @bbozo

Issue #88 seems more related to your issue. I think a locking mechanism will not work here because if the 2nd instance try to enqueue the same job after the first instance has finished the enqueing, both instance will have acquired the lock. 

Sidekiq-scheduler doesn't run jobs, it only enqueues jobs with the help of rufus-scheduler. Sidekiq is the piece who runs the jobs. So, using a rufus locking mechanism will prevent to enqueue the job at the same time, but will not prevent to enqueue the same job at different times, being very closely to each other.

Did this problem occur only once in the previous 5 days? What's the frequency of that job?
Can you post your config here. Feel free to edit any names, before posting. Thanks

**Comment by snmgian** [comment] 2016-12-22 19:02
Hi @bbozo, could you provide the schedule config you have? Thanks

**Comment by bbozo** [comment] 2016-12-23 14:10
Hey :) Sorry, completely forgot about your first mail, here comes, this is in the app initializer:

``` ruby
Sidekiq.configure_server do |config|
  threads = config.options[:concurrency] = ( ENV['MAX_WORKER_THREADS'] || 4 ).to_i
  config.redis = ConnectionPool.new(size: threads + 1, &redis_conn)
  config.options[:verbose] = App.log.log_level == :debug

  # set up Sidekiq Scheduler
  config.on(:startup) do
    schedule = YAML.load_erb_file(App.root + "/config/scheduler.yml")
    Dir[App.root + "/modules/*/config/scheduler.yml"].each do |yaml|
      schedule.merge! YAML.load_erb_file(yaml)
    end

    Sidekiq.schedule = schedule
    Sidekiq::Scheduler.reload_schedule!
  end
end
```

and the scheduler.yml of the job in question is as follows:

``` yaml
cutover_acquirer_name:
    description: "Description"
    class: "Acquirer::SettlementWorker"
    cron: "0 22 * * *  Europe/Zagreb"
    args: ["acquirer_ name", 1, 'AcquirerExportModule']
```

The schedule was loaded on all sidekiq workers in the cluster and it was loaded only once: the schedule for the job was listed only once in the recurring tab in the admin interface - I made sure that the sidekiq processes don't restart at the same time on different machines in the farm so that we don't skip scheduled jobs from time to time if a sysadmin fails to realize some app process is going on - I implemented a poor man's rolling restart with sleep basically for the sidekiq workers.

> Sidekiq-scheduler doesn't run jobs, it only enqueues jobs with the help of rufus-scheduler. Sidekiq is the piece who runs the jobs. So, using a rufus locking mechanism will prevent to enqueue the job at the same time, but will not prevent to enqueue the same job at different times, being very closely to each other.

It's been 2 weeks now since I dived deeply into the Rufus/Sidekiq-Scheduler code, so I may be wrong, but as far as I have seen Rufus doesn't have an in-built locking mechanism that would prevent him from pushing 2 jobs to sidekiq at the same time across a cluster so I was quick to blame it on Rufus, but if it's like that, why didn't this issue happen more often?

I'll check out the timestamps too, if the sysadmin screwed up NTP sync, I need to get access to the hosts first :full_moon_with_face: 

This happened once in 5 days or so and only on this job, it's possibly indicative that this is the heaviest of the jobs that I run at the moment via the scheduler. Since then I simply made it so that the scheduler is loaded and run only on one machine, but yeah, a long-term solution would be nice :)

**Comment by vergenzt** [comment] 2017-02-16 18:47
For what it's worth, this *_really_* needs to be documented better. I just spent about a day converting cron jobs to sidekiq-scheduler jobs because we were preparing to scale to multiple instances and I didn't want to have to implement locking for the cron schedules... aaaaand then I find this. :(

**Comment by bbozo** [comment] 2017-02-16 18:55
I hear you brother...

**Comment by dbenjamin57** [comment] 2017-02-20 12:43
Hi everyone, I think we are experiencing a similar issue but the effects are different for us. 
We recently moved away from Sidetiq due to in-compatibility with the new version of Sidekiq to Sidekiq Scheduler. 

We are running with a Kubernetes cluster and have between several to hundreds of servers running Sidekiq. Now, some of our less frequent jobs havent been running since the shift and I was wondering why. I looked at our log and saw something strange (log of a specific day, same as other days): 

<img width="953" alt="screen shot 2017-02-20 at 2 39 45 pm" src="https://cloud.githubusercontent.com/assets/1243052/23125454/80db93b0-f77a-11e6-8293-a0131629d227.png">

Now, even though we see the multiple enqueues, that job didnt run that day :(  I was trying to think about what the issue can be and this is what I was thinking:
Every time a new instance of a server comes up, it re-runs the scheduler and resets the counter for the 24h (1 day). Therefore, if I have even 1 new server coming to life in these 24 hours, my job will never run. 

Am I correct in my thesis?

**Comment by snmgian** [comment] 2017-02-20 14:39
Hi @dbenjamin57, Can you confirm that in your log there is not a message like the following?
```
2017-02-20T14:24:45.771Z 28528 TID-otq96t8bs INFO: queueing YourJobClass (health_check_alerts_mailer)
```

- What's the configuration for that job? 
- Does it uses sidekiq default queue? 
- It's the same configuration for each server?

**Comment by dbenjamin57** [comment] 2017-02-20 14:48
Hey @snmgian, I can confirm there is no log message like the above. When the job actually does run(pre sidekiq-scheduler, we saw the following in our log:

`"2017-02-16T00:00:07.175Z 1 TID-owj1x7v3k HealthCheckAlertsMailer JID c017bea3f47ec750d9901440 INFO: start"
`

The configuration for the job:
```
:queues:
  - [scrape_health_check, 2]
:schedule:
  health_check_alerts_mailer:
    every: 1d
    class: HealthCheckAlertsMailer
```

The job doesnt use the default sidekiq queue.  It uses the scrape healthcheck queue:

```
class HealthCheckAlertsMailer
  include Sidekiq::Worker
  sidekiq_options queue: :scrape_health_check
```

It's exactly the same configuration for all servers.

**Comment by snmgian** [comment] 2017-02-20 15:22
@bbozo I tried to reproduce your scenario, but didn't reproduce the problem. Despite that, I find and that could potentially lead to your problem:

* Servers in different datetimes. For example, if server1's time is `2017-02-20 00:03:00` and the other is living at `2017-02-19 00:03:00` then job will run on server2, and server1, twice the first day; after that it will run once per day.

Does that scenarios applied to your case?

**Comment by snmgian** [comment] 2017-02-20 15:50
@dbenjamin57 which version of sidekiq-scheduler are you using? Is it `< 2.1.0` ? 

Name queue inference was added recently, in `2.1.0`

**Comment by dbenjamin57** [comment] 2017-02-20 15:52
@snmgian continued to test the issue above. What I did is created a worker that is supposed to run every 1m. I started Sidekiq, let is run for 45s and then closed it. Ran sidekiq again, waited for 15s and saw the job didnt run. Waited another 45s and only then the job ran. 

Im guessing your scheduler that is not in a cron notation doesnt work properly. 

In reference to your question, Im using the latest version: 2.1.2

**Comment by snmgian** [comment] 2017-02-20 16:03
@dbenjamin57 `every` jobs are scheduled counting from startup. So If you start, wait for `59s`, restart, and then wait for `1s`, the job will not run. 

The internal counter is not persisted across restarts neither is persisted / published between idependent running instances.

So, if each of server's uptime is less that what your `every` job interval type is, the job will never run.

For that scenario you should use a `cron` type job.

**Comment by dbenjamin57** [comment] 2017-02-20 16:52
@snmgian got it. Thanks!

**Comment by bbozo** [comment] 2017-02-20 16:58
@snmgian unfortunately not, the servers are in sync with NTP (a PCI DSS requirement). But I'm wondering one thing, knowing that Rufus uses a file locking mechanism to prevent double execution, how could possibly `sidekiq-scheduler` work in a distributed environment?

**Comment by snmgian** [comment] 2017-02-20 17:41
@bbozo When a `cron` type job is going to be enqueued, sidekiq-scheduler stores in Redis (`ZADD` operation) the timestamp according to that execution (it's not `Time.now` but it is really close, it is the time at which the cron should have triggered). 

If that timestamp was not previously stored, it means that we are safe to enqueue the job; else, sidekiq-scheduler just discards it.

**Comment by snmgian** [comment] 2017-02-20 17:50
The main problem with Rufus `scheduler_lock` is that it only acquires the lock on startup, so if you have two servers (server-1 and server-2), `server-1` acquires the lock and `server-2` becomes disabled because it failed to lock, and then if `server-1` goes down, `server-2` will never come up.

Rufus `trigger_lock` will not be of help here, because if both servers try to enqueue the same instance of the job at slightly different times (like a time-delta of 500 ms, depending on latency and server load of course)  both server will happily acquire the lock, enqueue, and release the lock.

**Comment by bbozo** [comment] 2017-02-20 18:05
@snmgian hm, I understand. A different enqueing strategy would be needed to make this thing go away for good and not depend on something as fickle as NTP sync, network latencies, server load, startup & restart order of servers to make your day go bad. It's a *very* hard requirement to maintain 100% of the time.

I believe it's possible to be done well, but the delayed execution strategy would probably have to move away from Rufus and into Sidekiq, a tricky prospect, with it's own issues.

**Comment by snmgian** [comment] 2017-02-20 18:22
As soon as servers' time deltas don't exceed 24 hours, the current approach will work. Server load, latency and startup / restart order shouldn't affect cron job types.

Having a lock mechanism at sidekiq-scheduler side will work, perhaps at the expsense of smth (need put some thought here), but it's an option ...

**Comment by bbozo** [comment] 2017-04-11 19:29
@snmgian I managed to get hold of the server in question,

the job in question does a select statement and then stores the result into a DB row, the `created_at` timestamps are 0.001049s apart, so it seems to be a classic millisecond race condition.

The servers themselves should have been in sync via NTP too when the issue happened, I can only tell for sure they are in sync now.

My solution for a long time was to simply run only one sidekiq, now I'm rolling out with the same solution as https://github.com/moove-it/sidekiq-scheduler/issues/147#issuecomment-255490978 - to run only 1 process with the scheduler enabled.

Only way to reproduce it that I know of is to make a sidekiq job put a DB record every minute, honk up the number of sidekiq worker processes and then wait for double entries.

I'll try to set up something like that, somewhere.... Got any ideas where this could run for some days-weeks for free?

**Comment by snmgian** [comment] 2017-04-12 03:23
@bbozo It won't be a problem if servers are out-of-sync by a couple of minutes. 

1. Do you still have access to sidekiq's logs, for both servers, of the day the issue occurred?

You'll see smth like:
```
2017-04-12T02:02:08.742Z 7920 TID-oqyo9rhpo INFO: queueing SomeWorker (SomeWorker)
```

```
2017-04-12T02:02:08.745Z 7920 TID-oqyo9lmvo SomeWorker JID-f26dfe681e257aecbaba7737 INFO: start
```

2. Does each server share the same Redis instance? Do they have their own Redis instance independent of the other? Do you have Redis Cluster?

3. What's in `redis_conn` proc?

**Comment by bbozo** [comment] 2017-04-12 06:50
> Do you still have access to sidekiq's logs, for both servers, of the day the issue occurred?

Unfortunately not yet, I escalated the issue with the clients' sysadmins

> Does each server share the same Redis instance? Do they have their own Redis instance independent of the other? Do you have Redis Cluster?

No, same Redis instance

> What's in redis_conn proc?

``` ruby
redis_conn = proc {
  Redis.new(url: ENV['REDIS_URL'] || 'redis://localhost:6379', namespace: "myapp/#{RACK_ENV}") 
}
```

**Comment by bbozo** [comment] 2017-04-12 07:40
Here: https://gist.github.com/bbozo/d75f505247341081afd753f01cd53270

**Comment by snmgian** [comment] 2017-04-12 12:33
Thanks for looking into this.

It seems that the gist `zadd_race_condition.rb` you posted doesn't replicate what sidekiq-scheduler does.

Here: https://github.com/moove-it/sidekiq-scheduler/blob/master/lib/sidekiq/scheduler.rb#L304, `time` param, which is then passed in to `zadd` is not `Time.now`, it's the time at which the rufus-scheduler block should have been called.

See https://github.com/jmettraux/rufus-scheduler#schedule-blocks-arguments-job-time. ```The second argument is "time", it's the time when the job got cleared for triggering (not Time.now).```

I created a gist with a code sample, showing output console:

https://gist.github.com/snmgian/3a3ffe5c903cd9faf3bc9aeb64897671

**Comment by snmgian** [comment] 2017-04-12 12:41
The gist 100 rufus blocks every 6 seconds. Each block verifies if another block has ran for that timestamp. If no block has ran before, it increments a counter.

**Comment by snmgian** [comment] 2017-04-12 12:42
You mentioned that the `created_at` timestamps are 0.001049s apart. What's the value of those timestamps? Do the point to the same second?

**Comment by bbozo** [comment] 2017-04-12 15:15
> You mentioned that the created_at timestamps are 0.001049s apart. What's the value of those timestamps? Do they point to the same second?

Yes, they are postgres DB timestamps as recorded by [Sequel](https://github.com/jeremyevans/sequel) when the jobs *ran*, the timestamps are in microseconds: https://www.postgresql.org/docs/9.1/static/datatype-datetime.html

and the two records that got inserted were 0.001049s apart.

In the test code:

``` ruby
100.times.map do
  scheduler.cron(CRON_STRING) do |job, time|
    Concurrent::Future.execute do
      idempotent_job_enqueue(time)
    end
  end
end
```

I would wrap the future calls around the scheduler, to mimic multiple rufus'es in multiple processes ("on multiple hosts" heh), like so:

``` ruby
futures = 100.times.map do
  Process.fork do
    $cp = ConnectionPool.new { Redis.new }
    scheduler = Rufus::Scheduler.new
    scheduler.cron(CRON_STRING) do |job, time|
      idempotent_job_enqueue(time)
    end
    sleep(63)
    scheduler.shutdown(:wait)
    puts "!"
  end
end

$t1 = Time.now

sleep 80
report_end
```

but even this way, I have no idea what exactly Rufus does and how he generates that time variable - but what we do know is,  nothing in Rufus even attempts at being cluster-level atomic and depending on a barely not-so documented variable which was never meant to be a UUID to maintain uniqueness of tasks in a cluster is a not a safe thing to do, by a long shot :)

Or in other words, whatever Rufus does, at best, is to obfuscate the problem and make it harder to catch, it doesn't fix it, that `time` is not unique across a cluster and it's only a matter of "luck" to for it to be equal on different instances (which is why approximated it for more clear demonstration by doing a `time = Time.now`).

**Comment by snmgian** [comment] 2017-04-12 16:13
Rufus doesn't need to be cluster-level atomic. When rufus says 'hey, this is the job for this Time object', we check if the job has been already pushed for that time. `zadd` operation is atomic, and returns the number of elements added. So, if 10 process invoke `zadd` with the same value (seconds since epoch), only one will receive a response equal to `1`. That process is the one which then will enqueue the job into sidekiq, the other ones will discard it.

I'll take a deeper look at rufus source code ...

I tested what you've propsed, Here's the gist: https://gist.github.com/snmgian/5e008ea4e50fb6731b8e4a4a323cacc9

Couldn't run it on jRuby because fork is not aviable there.

**Comment by bbozo** [comment] 2017-04-12 16:29
@snmgian consider the example I gave, without Rufus. In that example we have to deal with 

1. a `Time.now` which is sometimes the same as a `Time.now` from a different process
2. with many processes trying to get a lock from `Redis` at the same time

and both are valid assumptions in the wild, there we managed to prove that yes: assuming Rufus sends 2 time objects of equal value within a cluster to 2 different `sidekiq-scheduler`s it's possible that the `zadd`-based locking code will not save us.

A general rule of thumb when going through different locking implementations is "if it doesn't use LUA scripting embedded in Redis, it's not safe" - see here https://github.com/kenn/redis-mutex/issues/5#issuecomment-14593136 - apparently the unlock code can't be done safely without LUA

And we know:

1. Rufus knows nothing of Redis - hence can't be an authority for cluster-level atomicity
2. Sidekiq-scheduler has no LUA blocks inside - hence can't be an authority for cluster-level atomicity

hence - there's nothing in the code base to make the locking non-racey :)

Does this reasoning make sense to you?

**Comment by snmgian** [comment] 2017-04-12 17:52
I'm sorry but I'm not following the reasoning :(

```
assuming Rufus sends 2 time objects of equal value within a cluster to 2 different sidekiq-schedulers it's possible that the zadd-based locking code will not save us.
```

why?

Lua is needed in cases which in order to invoke a Redis command you need  some result returned from a previous one, and you want that set of operations to be an atomic one. 

```
    registered = r.zadd(PUSHED_JOBS_SET_KEY, 0, 0)

    if registered
      puts "GO"
    end
```

(pipeline stuff and experation can be discarded here)

If we run that code, no matter which number of threads and process are running, `"GO"` will be printed only once (or zero if `0` is already in the set before the test starts, which is not our case). Why? Because `zadd` call will return `1` only once.

See this gist: https://gist.github.com/snmgian/04cc6c01675fcc989435ff3d10fa438b


As a side note, the benefit of having a LUA script instead of the above code would be performance, because you endup sending two commands (no-lua version) versus sending one command (lua version)

**Comment by snmgian** [comment] 2017-04-12 17:56
I just tested the snippet with a pool size of 100:

`$cp = ConnectionPool.new(size: 100, timeout: 100) { Redis.new }`

'GO' is printed only once

**Comment by bbozo** [comment] 2017-04-12 17:59
Yeah, I'm also benchmarking like crazy, but no luck producing the issue with Rufus in the mix: https://gist.github.com/bbozo/d75f505247341081afd753f01cd53270#file-zadd_with_rufus-rb

Yet Rufus should offer no additional locking, it's a bit puzzling

**Comment by snmgian** [comment] 2017-04-14 13:28
You need a locking mechanism when you want a whole set of operations to be isolated from another set of operations. 

What a lock does is to ensure that other client/process/thread doesn't modify data while another one is modifying/reading that same data (depending on the type of lock) and also prevents inconsistent reads.

Redis guarantees that only one command is executed at any given point in time. So if multiple clients are making concurrent requests, they will be served one at a time. Redis also guarantees that multiple commands are isolated if they are part of a `multi/exec` operation (commands are queued and executed at `exec`)

Redis locks are needed when you need to read, then make some computations (client side) based on that read, and then issue a write based on the previous step.

Sidekiq-scheduler needs to know if a job correspondong to point in time has been triggered before, and if it has not been triggered yet, mark it as triggerd and push it into sidekiq. Although it's a read/compute/write scenario, Redis provides a command to do that: `zadd`, which moves the compute part (checking for a boolean condition) to redis side.

Having a distributed locking mechanism will not help here. Let's say we have 2 sidekiq-scheduler instances, with their clocks out of sync by 60 seconds. Assume a schedule set to `cron: 0 * * * * *`. server-1 will acquire the lock, push the job into sidekiq, release the lock. After ~60 seconds, server-2 will happily acquire the lock, push to sidekiq, and release the lock. Sidekiq will endup executing the job twice. Am I missing something?

I think the base idea of storing the job's timestamp (or some info related to that, perhaps some counter instead of a timestamp), and checking if a job has not run previously should work.

I'll check again rufus-scheduler code to see if there's any chance of sending a "wrong" time object that could have caused this issue.

**Comment by snmgian** [comment] 2017-04-27 06:47
I found this in rufus-scheduler source code: https://github.com/jmettraux/rufus-scheduler/blob/master/lib/rufus/scheduler.rb#L570

So, it would be possible, under certain circumstances, to `EoTime.now` be a second later than the expected timestamp.

Such cirsumstances will be high load on the server in which the sidekiq-scheduler instance runs on, Redis latency combined with multiple jobs being scheduled or high frequency jobs, several jobs being scheduled at the same timestamp.

I just created an issue explaining this. See #181

**Closed** 2017-04-27 21:40 UTC

**Comment by lucasgomide** [comment] 2017-05-23 16:27
@bbozo @snmgian  I've implemented atomic key using Redis  [set key using NX option](https://redis.io/commands/set), it's just "alternative" (workaround) to fix this.

e.g
```ruby
class DummyScheduler
  def perform
    expire_in = 43200
    key = "ns:my-key"
    unless redis.set(key, 30, nx: true, ex: expire_in)
      return
    end
    // work here
  end
end

```

**Comment by daveharris** [comment] 2019-07-18 01:11
Thank you so much @lucasgomide, that seems to work brilliantly.

I'm not sure where you were getting the `redis` instance from but I had to go:
```
  Sidekiq.redis do |redis|
    redis.set("mutex:#{self.class.name.underscore}", 1, nx: true, ex: 1.hour)
  end
```
