### ISSUE TITLE
SideKiq worker not finishing 

### ISSUE THREAD

**Issue by wonderer007** [moove-it/sidekiq-scheduler#241] opened 2018-01-30 08:12 UTC
When I run a sidekiq worker it starts but never finish, it show me this in log

> 2018-01-30T08:08:01.243Z 994 TID-ouhfgrymk SendEmailWorker JID-69405aa9425c33647cc56afe INFO: start

When I restarted my development machine then it is finishing and showing me in log this

> 2018-01-30T08:08:01.243Z 994 TID-ouhfgrymk SendEmailWorker JID-69405aa9425c33647cc56afe INFO: start
> 2018-01-30T08:08:03.189Z 994 TID-ouhfgrymk SendEmailWorker JID-69405aa9425c33647cc56afe INFO: done: 1.946 sec

I am wondering If I had to face similar problem on production then It would require server restart. Can you please guide me what exactly this problem was ?

Thanks

**Comment by snmgian** [comment] 2018-02-02 02:13
It doesn't seem to be a problem related to neither sidekiq-scheduler nor sidekiq ... Is it a problem that occurs regularly? 

The first thing to do is to isolate the problem. Write a ruby script that does the same thing your job does. 

Run it several times, it should become stalled as in the same frequency when running the sidekiq job. If that's the case, then the problem is in the code that sends the email, and you'll have to take a look at it.

In the case that the script behaves ok, with no errors, and emails being sent successfully, then we should start looking at sidekiq...

I think it's a networking related issue, maybe the library you use to send emails retries several times until success, or maybe the server just hangs and timeout configuration at client side is not properly configured; but those are just a bunch of the possible reasons.

You could also try not restarting sidekiq, and just wait for about an hour and see if some error is either logged or not.

First thing is to find the cause of the problem, and to do that you must isolate each component until you find the problem.

Feel free to come back after you do some more testing. I'll leave this issue open in the meantime.

**Comment by snmgian** [comment] 2018-03-20 23:58
I'm closing this, but if you are still experiencing this issue, feel free to comment again and I'll re open it.

**Closed by snmgian** 2018-03-20 23:58 UTC
