### ISSUE TITLE
NotImplementedError when using with sidekiq_options and scheduler

### ISSUE THREAD

**Issue by justinweathersby** [moove-it/sidekiq-scheduler#354] opened 2021-09-08 19:13 UTC
Interesting issue. I have 3 different jobs that i run on sidekiq. One of which is called by the scheduler cron job. All 3 jobs work fine locally with no errors. But once deployed to Heroku using the Redis addon I cant seem to use `sidekiq_options` with the one job that is called via the scheduler. Even if I call it from the rails console it still throws a `NotImplementedError`. Seems to be something with the scheduler bc the other 2 jobs declare the `sidekiq_options` and are called via active model hooks and they work just fine.

**config/sidekiq.yml**
```
development:
  :concurrency: 1
production:
  :concurrency: 1
:queues:
  - default
  - mailers
  - google_calendar_updates
  - google_calendar_sync
```

**config/initializers/sidekiq.yml**
```
if ENV['REDIS_URL']
	Sidekiq.configure_client do |config|
		config.redis = { url: ENV['REDIS_URL'], network_timeout: 5 }
	end
	Sidekiq.configure_server do |config|
		config.redis = { url: ENV['REDIS_URL'], network_timeout: 5 }

		# Grab your scheduling yaml file to load into cron
		schedule_file = "config/schedule.yml"
		if File.exists?(schedule_file)
			Sidekiq.schedule = YAML.load_file(schedule_file)
			SidekiqScheduler::Scheduler.instance.reload_schedule!
		end
	end
end
```

**config/schedule.yml**
```
google_calendar_sync:
    cron: "*/15 * * * *"
    class: GoogleCalendarSyncJob
    queue: google_calendar_sync
    description: '...'
```

**job file**
```
class GoogleCalendarSyncJob < ApplicationJob
    queue_as :google_calendar_sync
    sidekiq_options queue: :google_calendar_sync, retry: 1, backtrace: 15
   
    def perform()
    ...
 ```

**Stacktrace:**
```
2021-09-08T18:45:00.189675+00:00 app[worker.1]: pid=4 tid=gsm8npeyg WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"google_calendar_sync","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"GoogleCalendarSyncJob","args":[{"job_class":"GoogleCalendarSyncJob","job_id":"fd31ccfd-b6c0-4b24-ab2a-ec19c969e2c9","provider_job_id":null,"queue_name":"google_calendar_sync","priority":null,"arguments":[],"executions":0,"exception_executions":{},"locale":"en","timezone":"Eastern Time (US & Canada)","enqueued_at":"2021-09-08T18:45:00Z"}],"jid":"e17aaba7d73ee19e6b08ff00","created_at":1631126700.1793797,"enqueued_at":1631126700.1794233},"jobstr":"{\"retry\":true,\"queue\":\"google_calendar_sync\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"GoogleCalendarSyncJob\",\"args\":[{\"job_class\":\"GoogleCalendarSyncJob\",\"job_id\":\"fd31ccfd-b6c0-4b24-ab2a-ec19c969e2c9\",\"provider_job_id\":null,\"queue_name\":\"google_calendar_sync\",\"priority\":null,\"arguments\":[],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"Eastern Time (US & Canada)\",\"enqueued_at\":\"2021-09-08T18:45:00Z\"}],\"jid\":\"e17aaba7d73ee19e6b08ff00\",\"created_at\":1631126700.1793797,\"enqueued_at\":1631126700.1794233}"}
2021-09-08T18:45:00.189689+00:00 app[worker.1]: pid=4 tid=gsm8npeyg WARN: NotImplementedError: NotImplementedError
2021-09-08T18:45:00.189722+00:00 app[worker.1]: pid=4 tid=gsm8npeyg WARN: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:47:in `perform'
2021-09-08T18:45:00.189723+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:40:in `block in perform_now'
2021-09-08T18:45:00.189723+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
2021-09-08T18:45:00.189724+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.3/lib/i18n.rb:313:in `with_locale'
2021-09-08T18:45:00.189725+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
2021-09-08T18:45:00.189725+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
2021-09-08T18:45:00.189725+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
2021-09-08T18:45:00.189726+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
2021-09-08T18:45:00.189726+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
2021-09-08T18:45:00.189727+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
2021-09-08T18:45:00.189727+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
2021-09-08T18:45:00.189727+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
2021-09-08T18:45:00.189727+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'
2021-09-08T18:45:00.189728+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2021-09-08T18:45:00.189728+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'
2021-09-08T18:45:00.189728+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
2021-09-08T18:45:00.189729+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:45:in `block in tag_logger'
2021-09-08T18:45:00.189729+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
2021-09-08T18:45:00.189729+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
2021-09-08T18:45:00.189730+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
2021-09-08T18:45:00.189730+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:45:in `tag_logger'
2021-09-08T18:45:00.189730+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
2021-09-08T18:45:00.189731+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
2021-09-08T18:45:00.189731+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
2021-09-08T18:45:00.189731+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:139:in `run_callbacks'
2021-09-08T18:45:00.189732+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:39:in `perform_now'
2021-09-08T18:45:00.189732+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:25:in `block in execute'
2021-09-08T18:45:00.189732+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
2021-09-08T18:45:00.189732+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
2021-09-08T18:45:00.189732+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
2021-09-08T18:45:00.189733+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
2021-09-08T18:45:00.189733+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:84:in `wrap'
2021-09-08T18:45:00.189733+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:71:in `wrap'
2021-09-08T18:45:00.189733+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
2021-09-08T18:45:00.189734+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
2021-09-08T18:45:00.189736+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
2021-09-08T18:45:00.189736+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:139:in `run_callbacks'
2021-09-08T18:45:00.189736+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:23:in `execute'
2021-09-08T18:45:00.189737+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.2/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
2021-09-08T18:45:00.189737+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:196:in `execute_job'
2021-09-08T18:45:00.189737+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
2021-09-08T18:45:00.189738+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
2021-09-08T18:45:00.189738+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:163:in `block in process'
2021-09-08T18:45:00.189739+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
2021-09-08T18:45:00.189739+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/job_retry.rb:112:in `local'
2021-09-08T18:45:00.189739+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
2021-09-08T18:45:00.189740+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/rails.rb:14:in `block in call'
2021-09-08T18:45:00.189740+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
2021-09-08T18:45:00.189740+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
2021-09-08T18:45:00.189740+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
2021-09-08T18:45:00.189740+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:71:in `wrap'
2021-09-08T18:45:00.189741+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/rails.rb:13:in `call'
2021-09-08T18:45:00.189741+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
2021-09-08T18:45:00.189741+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:257:in `stats'
2021-09-08T18:45:00.189742+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
2021-09-08T18:45:00.189742+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/job_logger.rb:13:in `call'
2021-09-08T18:45:00.189742+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
2021-09-08T18:45:00.189742+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/job_retry.rb:79:in `global'
2021-09-08T18:45:00.189743+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
2021-09-08T18:45:00.189743+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/logger.rb:11:in `with'
2021-09-08T18:45:00.189743+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/job_logger.rb:33:in `prepare'
2021-09-08T18:45:00.189744+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:123:in `dispatch'
2021-09-08T18:45:00.189744+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:162:in `process'
2021-09-08T18:45:00.189744+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:78:in `process_one'
2021-09-08T18:45:00.189745+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/processor.rb:68:in `run'
2021-09-08T18:45:00.189745+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:43:in `watchdog'
2021-09-08T18:45:00.189745+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.2.2/lib/sidekiq/util.rb:52:in `block in safe_thread'
2021-09-08T18:45:00.189746+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'```

**Comment by rdimartino** [comment] 2021-11-15 16:22
+1 We're attempting to migrate from `sidekiq-cron` because of https://github.com/ondrejbartas/sidekiq-cron/issues/291 but we're also running into this same issue. Works locally, but does not work when deployed in a sidekiq container on Amazon ECS

**Comment by marcelolx** [comment] 2021-11-15 16:42
I'll try to simulate this tomorrow. If someone can provide me with an app that would make it easy to simulate the problem, I would be happy.

**Comment by rdimartino** [comment] 2021-11-16 16:34
@marcelolx I created this which reproduces the issue for me: https://github.com/rdimartino/sidekiq-options-repro The README has the build/running instructions but let me know if you have any issues.

Some observations from testing to recreate this issue:

 - the Rails env must be production.

 - the schedule must be set in a separate YAML file and added to Sidekiq as part of the initializer with `reload_schedule!`. I could not recreate the `NotImplementedError` issue when using a `:schedule` key in `config/sidekiq.yml`

**Comment by marcelolx** [comment] 2021-11-17 11:00
@justinweathersby @rdimartino I believe the problem to both of you is that you're not loading the schedule when the Sidekiq `startup` lifecycle event is dispatched as we suggest in the docs https://github.com/moove-it/sidekiq-scheduler#load-the-schedule-from-a-different-file

@rdimartino I made the following changes in the Sidekiq initializer and now I'm not seeing those errors

```diff
  Sidekiq.configure_server do |config|
    config.redis = { url: 'redis://redis' }
+   config.on(:startup) do
      Sidekiq.schedule = YAML.load_file 'config/sidekiq-scheduler.yml'
      Sidekiq::Scheduler.reload_schedule!
+   end
  end
  
  Sidekiq.configure_client do |config|
    config.redis = { url: 'redis://redis' }
  end
```

**Comment by marcelolx** [comment] 2021-11-17 11:05
@justinweathersby I believe that if you change your initializer to the following, it should work as well, sorry for the delay.

```diff
if ENV['REDIS_URL']
  Sidekiq.configure_client do |config|
    config.redis = { url: ENV['REDIS_URL'], network_timeout: 5 }
  end
  
  Sidekiq.configure_server do |config|
    config.redis = { url: ENV['REDIS_URL'], network_timeout: 5 }
+   config.on(:startup) do
      # Grab your scheduling yaml file to load into corn
      schedule_file = "config/schedule.yml"
      if File.exists?(schedule_file)
        Sidekiq.schedule = YAML.load_file(schedule_file)
        SidekiqScheduler::Scheduler.instance.reload_schedule!
      end
+    end
  end
end
```

**Comment by rdimartino** [comment] 2021-11-17 14:44
@marcelolx Aha! Yes, thank you, that fixes the issue for us. Appreciate the help! I should've payed closer attention to the examples, but didn't notice that detail when migrating from `sidekiq-cron`. Sorry for the trouble and thanks again!

**Comment by marcelolx** [comment] 2021-11-17 14:46
Nice @rdimartino, you're welcome!

I'll close this issue, @justinweathersby if this doesn't fix your problem let me know.

**Closed by marcelolx** 2021-11-17 14:46 UTC
